services:
  dvinyl-app:
    build: .
    restart: unless-stopped
    ports:
      - "3099:80"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/dvinyl
      - VINYL_PORT=80
      - PROD=true
      - SESSION_SECRET=${SESSION_SECRET}
      - AUTH_USERS=${AUTH_USERS}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - EAN_SEARCH_TOKEN=${EAN_SEARCH_TOKEN}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mongodb
    networks:
      - dvinyl_net

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - dvinyl_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - dvinyl-app
    networks:
      - dvinyl_net

networks:
  dvinyl_net:

volumes:
  mongo_data:
